version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.go
    restart: always
    expose:
      - "8000"
    volumes:
      - ./sql_app.db:/app/sql_app.db

  caddy:
    image: caddy:2-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - CADDY_DOMAIN=${CADDY_DOMAIN}

volumes:
  caddy_data:
  caddy_config:
