services:
  - type: web
    name: class-coordinator-app
    runtime: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 8000
    domains:
      - t1.kfamcloud.com
